#!/usr/bin/env php
<?php
namespace think;

// 命令行入口文件
// 加载基础文件
use app\plugs\PlugsInitEvent;

require __DIR__ . '/vendor/autoload.php';

$console = (new App())->console;
// 应用初始化
try {
    PlugsInitEvent::app_init('cli');
} catch (db\exception\DataNotFoundException | db\exception\DbException $e) {
    var_dump($e);
}
$console->run();